### ISSUE TITLE
Add opportunity to change type of array size

### ISSUE THREAD

**Issue by ablearthy** [0xd34df00d/binary-generic-combinators#1]
By default `binary` parses an array in [this](https://hackage.haskell.org/package/binary-0.10.0.0/docs/src/Data.Binary.Class.html#line-578) way. It parses Int (64 bit BE), but there's might be situation when length is 32 bit int (or 16 bit int). 
```
--N--|--Elem 0--|--Elem 1--|....|--Elem N--
 U32 |    T     |  ...     | .. |    T
-----|----------|----------|----|---------
```
Is there beautiful way to do it?

**Comment by 0xd34df00d** [comment]
Yep! [`CountedBy`](https://hackage.haskell.org/package/binary-generic-combinators-0.4.2.0/docs/Data-Binary-Combinators.html#t:CountedBy) should cover this use case. In particular, you'll have something like
```haskell
data MyRecord = MyRecord
  { myArray :: CountedBy Word32 MyType,
  ...
  } deriving (Generic, Binary)
```
and then use `getCounted` on the `myArray` field to access the underlying `[MyType]`.

Although, in hindsight, using `[]` might be suboptimal, especially if you expect to have more than a few elements in the array. Please let me know if this would be an issue for you — I'd be happy to hack on the library to support other sequential container types!

**Comment by ablearthy** [comment]
I feel embarrassed to ask for help, however, for two days I can't understand should or not I use this library in my case.
I write the [MS-CFB](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/50708a61-81d9-49c8-ab9c-43c98a795242) parser (FAT in the file). The problem is that parser should read parts of data from different sectors. Therefore, reading from file more effective (because of `hSeek`) rather then from `ByteString`. Although, there are two cases (reading from file and from `ByteString`)

Let me show peace of code that parses [DIFAT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/0afa4e43-b18f-432a-9917-4f276eca7a73) sectors (DIFAT contains information about FAT sectors location) and concatenates them together. 

```haskell
type DIFAT = [Word32]

type SectorGetter m = Word32 -> m BL.ByteString 
newtype Config m = Config {secGetter :: SectorGetter m}

getDIFATSector :: Int -> Get (DIFAT, Word32)
getDIFATSector count = do
  values <- getMany getWord32le count
  return (take (length values - 1) values, last values)

getDIFAT :: (Monad m) => Header -> Reader (Config m) (m DIFAT)
getDIFAT header = do
  r <- asks secGetter
  let secSize = _sectorSize header `div` 4
  return $ go r (_firstDifatSectorLoc header) (fromIntegral secSize)
  where
    go :: (Monad m) => SectorGetter m -> Word32 -> Word32 -> m DIFAT
    go sg sec size = do
      l <- sg sec
      let (head, tail) = runGet (getDIFATSector $ fromIntegral size) l -- getDIFATSector :: Int -> Get (DIFAT, Word32)
      case tail of
        0xFFFFFFFE -> return head
        _ -> fmap (head ++) (go sg tail size) -- ineffective
```
`Header` contains `_firstDifatSectorLoc`.
There is function that gets current sector from a file:
```haskell
getSectorFromFile :: Handle -> Word32 -> Word32 -> IO BL.ByteString
getSectorFromFile hdl secSize secNo = do
  hSeek hdl AbsoluteSeek $ toInteger $ secSize * (secNo + 1)
  BL.hGet hdl (fromIntegral secSize)
```
In the `main` it's just curried, thus, we get `Word32 -> IO BL.ByteString`. Then we can create `Config`, then call `runReader`.
I have two questions:
  1) Is this library help to solve the problem?
  2) Is there something wrong with `getDIFAT`?

**Comment by ablearthy** [comment]
I think you are not interested in that, and if it is so then, please, let me know. 
<details>
   <sumary>Spoiler</summary>
 
    I don't want to spend your time, but it's really difficult to find examples of parsing binary data. 
</details>
~~Otherwise if you don't mind we could discuss on this problem~~

**Comment by ablearthy** [comment]
Thanks a lot!
